name: Ssc
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/Ssc.yml'
      - 'echo.sh'
permissions: write-all
jobs:
  build:
    name: 'See progress'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Start process'
        run: |
          # Kakathic         
          sudo apt install g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-gnu-
          ./ssc -i /system/bin/sh echo.sh kaka.sh
      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          name: upload
          tag_name: tmp
          files: kaka.sh
